### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe With kafka ",
  "email": "Johndoe@gmail.com",
  "dateOfBirth": "2001-02-18",
  "address": "Laatatra sidi bennour"
}



###
