server:
  port: 4004
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## Rest Client --> http://localhost:4004/api/patients/
            ## API GATEWAY --> http://patient-service:4000/patients
            ##PATIENT SERVICE  (SPRING BOOT APP)-->/patients -->patients array
            - id : auth-service-routes
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1


            - id : patient-service-routes
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id : api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients , /v3/api-docs

            ## REST CLIENT : http://localhost:4004/api-docs/patient
            ## API GATEWAY : http://patient-service:4000/v3/api-docs
